// source: https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values#Enchantment_IDs

export const EnchantmentTypes = {
  0: "protection",
  1: "fire_protection",
  2: "feather_falling",
  3: "blast_protection",
  4: "projectile_protection",
  5: "thorns",
  6: "respiration",
  7: "depth_strider",
  8: "aqua_affinity",
  9: "sharpness",
  10: "smite",
  11: "bane_of_arthropods",
  12: "knockback",
  13: "fire_aspect",
  14: "looting",
  15: "efficiency",
  16: "silk_touch",
  17: "unbreaking",
  18: "fortune",
  19: "power",
  20: "punch",
  21: "flame",
  22: "infinity",
  23: "luck_of_the_sea",
  24: "lure",
  25: "frost_walker",
  26: "mending",
  27: "binding_curse",
  28: "vanishing_curse",
  29: "impaling",
  30: "riptide",
  31: "loyalty",
  32: "channeling",
  33: "multishot",
  34: "piercing",
  35: "quick_charge",
  36: "soul_speed",
  37: "swift_sneak",
}